const URL = 'https://api.nomoreparties.co';
const SHORT_MOVIE_DURATION = 40;
const CARDS_TO_ADD_FOR_MIN_WW = 2;
const CARDS_TO_ADD_FOR_MAX_WW = 3;
const CARDS_COUNT_FOR_MIN_WW = 5;
const CARDS_COUNT_FOR_MEDIUM_WW = 8;
const CARDS_COUNT_FOR_MAX_WW = 12;

export {
  URL,
  SHORT_MOVIE_DURATION,
  CARDS_TO_ADD_FOR_MIN_WW,
  CARDS_TO_ADD_FOR_MAX_WW,
  CARDS_COUNT_FOR_MIN_WW,
  CARDS_COUNT_FOR_MEDIUM_WW,
  CARDS_COUNT_FOR_MAX_WW,
};
